CrudNetCore5/Models/ErrorViewModel.cs
using System;

namespace CrudNetCore5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNetCore5/Controllers/HomeController.cs
using CrudNetCore5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetCore5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNetCore5/Controllers/LibrosController.cs
using CrudNetCore5.Data;

using CrudNetCore5.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CrudNetCore5.Controllers
{
    public class LibrosController : Controller
    {
        //Primero importamos el applicationdbcontext porque eso nos permite acceder a la base de datos
        private readonly ApplicationDbContext _context;
        //Constructor para inicializar el acceso a la db
        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public IActionResult Index()
        {
            IEnumerable<Libro> listaLibros = _context.Libro;
            //Lo lleva a la vista de Libros
            return View(listaLibros);
        }

        //Http Get Crear Libro
        public IActionResult Create()
        {
            //Retorna un formulario
            return View();
        }

        //Http Post Crear Libro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Libro libro)
        {
            //Validando los modelos
            if (ModelState.IsValid)
            {
                _context.Libro.Add(libro);
                _context.SaveChanges();

                //Un mensaje en patalla que nos indique que el libro fue creado
                TempData["mensaje"] = "El libro fue creado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        //Http Get Edit: Buscamos el libro y retornamos al view
        public IActionResult Edit(int? id)
        {
            if(id== null|| id == 0)
            {
                return NotFound();
            }

            //Obtener libro
            var libro = _context.Libro.Find(id);

            if(libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        //Http Post Actualizar Libro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Libro libro)
        {
            //Validando los modelos
            if (ModelState.IsValid)
            {
                _context.Libro.Update(libro);
                _context.SaveChanges();

                //Un mensaje en patalla que nos indique que el libro fue actualizado
                TempData["mensaje"] = "El libro se ha actualizado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Http Get Delete: Buscamos el libro y retornamos al view
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Obtener libro
            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        //Http Post Eliminar Libro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLibro(int? id)
        {
            //Obtener el libro por id
            var libro = _context.Libro.Find(id);

            if(libro == null)
            {
                return NotFound();
            }

                _context.Libro.Remove(libro);
                _context.SaveChanges();

                //Un mensaje en patalla que nos indique que el libro fue eliminado
                TempData["mensaje"] = "El libro se ha eliminado correctamente";
                return RedirectToAction("Index");
            
        }
    }
}

CrudNetCore5/Views/Libros/Create.cshtml
@model CrudNetCore5.Models.Libro

@{
    ViewData["Title"] = "Crear Nuevo Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear Libro</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Libro</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear Libro" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>


@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" />}
}

CrudNetCore5/Views/Libros/Delete.cshtml
@model CrudNetCore5.Models.Libro

@{
    ViewData["Title"] = "Eliminar Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar libro</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar Libro</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteLibro">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" disabled/>
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" disabled/>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" disabled />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" disabled/>
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" disabled/>
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar Libro" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>


@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" />}
}

CrudNetCore5/Views/Libros/Edit.cshtml
@model CrudNetCore5.Models.Libro

@{
    ViewData["Title"] = "Actualizar Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar libro</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar Libro</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar Libro" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>


@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" />}
}

CrudNetCore5/Views/Libros/Index.cshtml
<!--Importamos el modelo, ya que el controlador ya obtiene todos los datos de la bd-->
@model IEnumerable<CrudNetCore5.Models.Libro>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Libros</h1>

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros">Agregar Nuevo Libro</a>
        </div>
    </div>

    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                        <td>@Html.DisplayNameFor(m => m.Titulo)</td>
                        <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                        <td>@Html.DisplayNameFor(m => m.FechaLanzamiento)</td>
                        <td>@Html.DisplayNameFor(m => m.Autor)</td>
                        <td>@Html.DisplayNameFor(m => m.Precio)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>@item.Id</td>
                            <td>@item.Titulo</td>
                            <td>@item.Descripcion</td>
                            <td>@item.FechaLanzamiento</td>
                            <td>@item.Autor</td>
                            <td>@item.Precio</td>
                            <td>
                                <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id"
                                   class="btn btn-warning">
                                    Editar
                                </a>
                                <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id"
                                   class="btn btn-danger">
                                    Eliminar
                                </a>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>

</div>